version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    commit-message:
      prefix: "chore"
    pull-request-branch:
      delete-branch: true
    allow:
      - dependency-type: "all"
        update-type: "security"
